packages/sd-jwt/__tests__/verify.test.ts
packages/sd-jwt/src/types.ts
packages/sd-jwt/src/verify.ts

* Refine the list of supported signature algorithms
As for [SD-JWT](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-04.html#name-creating-an-sd-jwt) reference:
> An SD-JWT is a JWT that MUST be signed using the Issuer's private key. It MUST use a JWS asymmetric digital signature algorithm. It MUST NOT use none or an identifier for a symmetric algorithm (MAC).

[SIW-236] Support asymmetric algorithms only

---

apps/io-func-wallet-solution-backend/src/infra/http/handlers/create-wallet-instance-attestation.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/get-entity-configuration.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/utils.ts

According to [OIDC Federation](https://openid.net/specs/openid-connect-federation-1_0.html#section-6.2) change the response `Content-Type` to  `application/entity-statement+jwt`

chore: Change JWT content-type

---

apps/io-func-wallet-solution-backend/src/infra/http/handlers/create-wallet-instance-attestation.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/get-entity-configuration.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/utils.ts

According to: https://github.com/pagopa/io-wallet/pull/16#discussion_r1262353223

chore: Change content type

---

apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/create-wallet-instance-attestation.spec.ts

Fix unit test for https://github.com/pagopa/io-wallet/pull/23

test: Fix unit test

---

apps/io-func-wallet-solution-backend/src/encoders/entity-configuration.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/create-wallet-instance-attestation.spec.ts
apps/io-func-wallet-solution-backend/src/wallet-provider.ts

Add `removeTrailingSlash` to:
- `LoAUri`
- `authority_hints`

chore: Add removeTrailingSlash to other fields

---

apps/io-func-wallet-solution-backend/openapi.yaml
apps/io-func-wallet-solution-backend/src/app/main.ts
apps/io-func-wallet-solution-backend/src/infra/azure/cosmos/nonce.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/create-wallet-instance.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/get-nonce.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/create-wallet-instance.ts
apps/io-func-wallet-solution-backend/src/nonce.ts
apps/io-func-wallet-solution-backend/src/wallet-instance-request.ts
apps/io-func-wallet-solution-backend/src/wallet-instance.ts
yarn.lock

1. Update OpenAPI file with `POST /wallet-instance` endpoint
2. Added validate challenge step in `CreateWalletInstanceHandler` handler
3. Added unit tests

chore: [SIW-964] Add nonce validation

---

apps/io-func-wallet-solution-backend/src/__test__/jwk.spec.ts
apps/io-func-wallet-solution-backend/src/__test__/verifier.spec.ts
apps/io-func-wallet-solution-backend/src/entity-configuration.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/android/__test__/assertion.spec.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/android/__test__/attestation.spec.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/ios/__test__/assertion.spec.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/ios/__test__/attestation.spec.ts
apps/io-func-wallet-solution-backend/src/infra/crypto/__test__/signer.spec.ts
apps/io-func-wallet-solution-backend/src/infra/crypto/signer.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/create-wallet-attestation.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/create-wallet-instance.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/get-nonce.spec.ts
apps/io-func-wallet-solution-backend/src/signer.ts
apps/io-func-wallet-solution-backend/src/wallet-attestation.ts

Some old unit tests have been refactored
To be more similar to the most recent ones

chore: [SIW-1075] Refactor tests

---

apps/io-func-wallet-solution-backend/src/app/main.ts

Changed `authLevel` functions configuration from `anonymous` to `function`

feat: [SIW-1078] Updated authLevel in functions configuration

---

apps/io-func-wallet-solution-backend/openapi.yaml
apps/io-func-wallet-solution-backend/src/app/main.ts
apps/io-func-wallet-solution-backend/src/infra/azure/cosmos/wallet-instance.ts
apps/io-func-wallet-solution-backend/src/infra/azure/functions/get-user-by-fiscal-code.ts
apps/io-func-wallet-solution-backend/src/infra/azure/functions/get-user-id-by-fiscal-code.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/create-wallet-instance.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/get-user-by-fiscal-code.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/__test__/get-user-id-by-fiscal-code.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/create-wallet-instance.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/get-user-by-fiscal-code.ts
apps/io-func-wallet-solution-backend/src/infra/pdv-tokenizer/client.ts
apps/io-func-wallet-solution-backend/src/user.ts
apps/io-func-wallet-solution-backend/src/wallet-instance.ts

1. Added header `x-iowallet-user-id` in `createWalletInstance` function
2. Created `WalletInstanceRepository` type and class implementation
3. Added `insertWalletInstance` as the last step in `createWalletInstance` function handler
4. Updated unit tests
5. Renamed some stuff

chore: [SIW-456] Add device registration

---

.github/workflows/code-review.yaml

Changed the `code-review` workflow with the centralized one

chore: updated code-review workflow

---

apps/io-func-wallet-solution-backend/package.json
yarn.lock

Updated `@pagopa/handler-kit-azure-func` and added `@pagopa/handler-kit` dependencies

chore: Updated handler-kit dependencies

---

apps/io-func-wallet-solution-backend/package.json
yarn.lock

fix: updated @pagopa/handler-kit-azure-func dependency

---

apps/io-func-wallet-solution-backend/src/__test__/jwk.spec.ts
apps/io-func-wallet-solution-backend/src/attestation-service.ts
apps/io-func-wallet-solution-backend/src/entity-configuration.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/android/__test__/assertion.spec.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/android/assertion.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/android/index.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/ios/__test__/config.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/ios/assertion.ts
apps/io-func-wallet-solution-backend/src/infra/attestation-service/ios/index.ts
apps/io-func-wallet-solution-backend/src/infra/crypto/__test__/signer.spec.ts
apps/io-func-wallet-solution-backend/src/infra/http/handlers/get-entity-configuration.ts
apps/io-func-wallet-solution-backend/src/jwk.ts
apps/io-func-wallet-solution-backend/src/wallet-attestation.ts
apps/io-func-wallet-solution-backend/src/wallet-instance.ts

1. Updated `JWKPublicKey` type (with optional `kid`)
2. Added `validateJwkKid` function
3. Check if `kid` is `undefined` in `getEntityConfiguration` and `createWalletAttestation `
4. Replaced `JWK` `jose` type with the custom type `JWKPublicKey`
5. Added decode from `JWK` to `JWKPublicKey` in validate attestation functions
6. Added unit tests

chore: [SIW-1126] Replaced JWK jose type with JWKPublicKey type

---

apps/io-func-wallet-solution-backend/openapi.yaml
apps/io-func-wallet-solution-backend/src/app/main.ts

fix: fix OpenAPI

---

.github/workflows/pr_infra.yaml
.github/workflows/release_infra.yaml

Add infra workflows
Automation to verify and apply infra changes

[EC-295] Add infra workflows

---

.github/workflows/release_infra.yaml
.gitignore
.pre-commit-config.yaml
infra/identity/prod/westeurope/.terraform.lock.hcl
infra/repository/.terraform.lock.hcl
infra/resources/_modules/key_vaults/key_vault_wallet.tf
infra/resources/_modules/key_vaults/main.tf
infra/resources/_modules/key_vaults/outputs.tf
infra/resources/_modules/key_vaults/variables.tf
infra/resources/prod/.terraform.lock.hcl
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/locals.tf
infra/resources/prod/main.tf

Add Key Vault
Update .gitignore to include TF lock files
Commented out tf validate for the "usual" issue with local modules
IO Wallet needs a key vault, doesn't it?

[SIW-990] Add KeyVault for IO Wallet

---

infra/resources/_modules/networking/main.tf
infra/resources/_modules/networking/outputs.tf
infra/resources/_modules/networking/subnet_wallet.tf
infra/resources/_modules/networking/variables.tf
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Add subnet for function app outbound connectivity
Other resources are private, reachable through private endpoints

[SIW-985] Add subnet for Wallet Function App

---

apps/io-func-wallet-solution-backend/openapi.yaml

chore: updated OpenAPI

---

apps/io-func-wallet-solution-backend/openapi.yaml

chore: added UserDetailView in openapi.yaml

---

infra/identity/prod/westeurope/main.tf
infra/resources/_modules/cosmos/cosmos_accounts.tf
infra/resources/_modules/cosmos/cosmos_containers.tf
infra/resources/_modules/cosmos/cosmos_databases.tf
infra/resources/_modules/cosmos/locals.tf
infra/resources/_modules/cosmos/main.tf
infra/resources/_modules/cosmos/networking.tf
infra/resources/_modules/cosmos/outputs.tf
infra/resources/_modules/cosmos/rbac.tf
infra/resources/_modules/cosmos/variables.tf
infra/resources/_modules/key_vaults/key_vault_key_cosmos.tf
infra/resources/_modules/key_vaults/key_vault_wallet.tf
infra/resources/_modules/key_vaults/outputs.tf
infra/resources/_modules/key_vaults/rbac.tf
infra/resources/_modules/key_vaults/variables.tf
infra/resources/prod/.terraform.lock.hcl
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Add Cosmos Account with its own database and container
Add private endpoint
Add customer-managed-key in key vault and accessed by the cosmos via managed identity

[SIW-993] Add Cosmos DB

---

.github/workflows/pr_gh_runner.yaml
.github/workflows/release_gh_runner.yaml
infra/github-runner/README.md
infra/github-runner/prod/.terraform.lock.hcl
infra/github-runner/prod/locals.tf
infra/github-runner/prod/main.tf
infra/github-runner/prod/outputs.tf

Add GitHub self-hosted runner
Useful to run workflow in vnet context

[EC-297] Add GitHub self-hosted runner

---

.github/workflows/release_gh_runner.yaml

Fix typo in workflow name

---

.changeset/metal-penguins-visit.md

chore: run changeset

---

.changeset/two-hotels-brush.md
apps/io-wallet-user-func/openapi.yaml

chore: update api title

---

apps/io-wallet-user-func/openapi.yaml
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-attestation.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-attestation.ts
apps/io-wallet-user-func/src/infra/http/handlers/utils.ts

chore: updated createWalletAttestation status code on success

---

apps/io-wallet-user-func/src/infra/attestation-service/index.ts

Since the stringify of a JWK may be different between operating systems as the JWK may have optional attributes that do not need to be computed, the representation of the JWK has been changed to its thumbprint being unique instead.

fix: [SIW-1169] Fix `client_data` attributes

---

.github/workflows/release.yaml
.github/workflows/user_function_deploy.yaml

1. Updated `release` workflow
2. Added `user_function_deploy` workflow

chore: updated GitHub workflows

---

.github/workflows/pr_infra.yaml
.pre-commit-config.yaml
infra/resources/_modules/cdn/alerts.tf
infra/resources/_modules/cdn/cdn.tf
infra/resources/_modules/cdn/cdn_hostname.tf
infra/resources/_modules/cdn/dns.tf
infra/resources/_modules/cdn/locals.tf
infra/resources/_modules/cdn/main.tf
infra/resources/_modules/cdn/outputs.tf
infra/resources/_modules/cdn/storage_account.tf
infra/resources/_modules/cdn/variables.tf
infra/resources/_modules/iam/cdn_storage_account.tf
infra/resources/_modules/iam/variables.tf
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Add CDN
Add Storage Account behind the CDN
Add custom domain for CDN
Add IAM role for function to get read access to the CDN storage account

[SIW-989] Add CDN for static files

---

infra/resources/_modules/cdn/storage_account.tf

Delete Cloud Defender resource for CDN Storage Account
Option not supported in ItalyNorth region

[SIW-989] Delete Cloud Defender resource for CDN Storage Account

---

.github/workflows/release.yaml

chore: tentative fix gh wf

---

.changeset/dull-pillows-check.md
.github/workflows/release.yaml

Added `fetch-depth: 0` in the checkout in the `release` GH workflow
Changeset does not work without it

fix: updated release workflow

---

infra/identity/prod/westeurope/main.tf
infra/resources/_modules/function_apps/data.tf
infra/resources/_modules/function_apps/key_vault_secrets.tf
infra/resources/_modules/function_apps/variables.tf
infra/resources/prod/main.tf

Add Function App User default key to Key Vault
Key must be grabbed and used by app backend

[SIW-1167] Add Function App User default key to keyvault

---

infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Move Function App default key to weu-common Key Vault
App Gateway module gets secrets from common kv

[SIW-1167] Move Function App default key to weu-common Key Vault

---

.github/workflows/user_function_deploy.yaml

Disable deployment on Function App staging slot 
Target function App doesn't have a staging slot

chore: Disable deployment on Function App staging slot 

---

.changeset/grumpy-numbers-return.md
apps/io-wallet-user-func/host.json

fix: add function route prefix

---

.github/workflows/user_function_deploy.yaml

The trigger is for changes in the `CHANGELOG.md` file
Otherwise the deploy pipeline is triggered for every push to the main branch

chore: user_function_deploy.yaml workflow

---

.changeset/green-otters-roll.md
apps/io-wallet-user-func/package.json

chore: renamed coverage script as test:coverage

---

infra/resources/_modules/iam/cdn_storage_account.tf
infra/resources/prod/.terraform.lock.hcl
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Add `Storage Blob Data Owner` role to `io-p-adgroup-admin` over CDN Storage Account
Add `Storage Blob Data Owner` role to `io-p-adgroup-developers` over CDN Storage Account
Add `Key Vault Administrator` role to `io-p-adgroup-admin` over KeyVault
Both devs and devops need access to these resources

chore: Add IAM roles to 'io-p-adgroup-admin'

---

infra/identity/prod/main.tf
infra/resources/_modules/iam/cdn_storage_account.tf
infra/resources/_modules/iam/key_vault_iam.tf

Add `Role Based Access Control Administrator` role to CD identity over wallet resource group
A couple of renames
CD workflow needs to delete IAM roles too

chore: Add 'Role Based Access Control Administrator' role to CD identity

---

.changeset/stupid-ears-sell.md
apps/io-wallet-user-func/package.json
yarn.lock

So the `applicationinsights` dependency is updated to the `2.9.5` version. This could be one of the reasons why the function app is not correctly deployed

chore: Updated @pagopa/ts-commons

---

.changeset/lovely-tomatoes-lie.md
apps/io-wallet-user-func/local.settings.json.example
apps/io-wallet-user-func/package.json
apps/io-wallet-user-func/src/app/config.ts
apps/io-wallet-user-func/src/app/main.ts
infra/resources/_modules/function_apps/locals.tf
infra/resources/_modules/function_apps/variables.tf
infra/resources/prod/main.tf
yarn.lock

Removed connection strings for Cosmos DB and storage account in favor of using managed identities

chore: [SIW-1199] Removed cosmos and storage account connection strings

---

infra/resources/_modules/iam/cosmos_iam.tf

Fix role definition id
Role definition id was wrong

fix: Assign CosmosDB Contributor role to io-p-adgroup-admin and io-p-adgroup-developers groups

---

infra/resources/_modules/function_apps/locals.tf

fix: Add EntityConfigurationStorageContainerName env var

---

.changeset/rotten-jokes-act.md
apps/io-wallet-user-func/host.json
infra/resources/_modules/function_apps/function_app_user.tf

fix: [SIW-1205] add /wallet path

---

apps/io-wallet-user-func/src/encoders/entity-configuration.ts
apps/io-wallet-user-func/src/encoders/wallet-attestation.ts
apps/io-wallet-user-func/src/wallet-attestation.ts

Alignment with new technical rules based on ongoing integration tests

fix: [SIW-1279] Alignment with new technical rules

---

.changeset/selfish-coins-raise.md
apps/io-wallet-user-func/local.settings.json.example
apps/io-wallet-user-func/src/infra/azure/cosmos/wallet-instance.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-instance.spec.ts
apps/io-wallet-user-func/src/wallet-instance.ts
apps/io-wallet-web-func/local.settings.json.example
apps/io-wallet-web-func/src/app/main.ts
apps/io-wallet-web-func/src/infra/azure/cosmos/wallet-instance.ts
apps/io-wallet-web-func/src/infra/azure/functions/create-wallet-instance.ts
apps/io-wallet-web-func/src/infra/handlers/__test__/create-wallet-instance.spec.ts
apps/io-wallet-web-func/src/infra/handlers/create-wallet-instance.ts
apps/io-wallet-web-func/src/infra/http/handlers/__test__/get-current-wallet-instance.status.spec.ts
apps/io-wallet-web-func/src/wallet-instance.ts

1. Added `createWalletInstance` in `io-wallet-web-func` workspace
2. Added unit tests
When a new wallet instance is created in the `user-func` function app, the `createWalletInstance` function in the `web-func` function app is triggered to insert the record into the `web` database as well

feat: [SIW-1259] Added createWalletInstance function

---

.changeset/hot-bananas-end.md
apps/io-wallet-user-func/src/app/config.ts
infra/resources/_modules/function_apps/locals.tf

Align the bundle identifier with the production app

fix: Change Android bundle identifier

---

.changeset/lucky-fireants-cheat.md
apps/io-wallet-user-func/src/app/main.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-attestation.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-instance.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/get-user-by-fiscal-code.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-attestation.ts
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-instance.ts
apps/io-wallet-user-func/src/infra/http/handlers/get-user-by-fiscal-code.ts
apps/io-wallet-user-func/src/infra/http/jwt-validator.ts
apps/io-wallet-user-func/src/infra/http/whitelisted-user.ts
apps/io-wallet-user-func/src/infra/trial-system/client.ts
apps/io-wallet-user-func/src/user.ts

1. Removed trial system checks from `createWalletInstance`, `createWalletAttestation` and `getUserByFiscalCode` functions
2. Changed the calls to the trial system. Now we use the fiscal code instead of the pdv ID for simplicity

chore: [SIW-1016] updated trial system integration

---

.changeset/strong-lizards-cry.md
apps/io-wallet-user-func/src/app/config.ts
infra/resources/_modules/function_apps/locals.tf
infra/resources/prod/locals.tf

chore: Added environment variables

---

.changeset/many-bats-melt.md
apps/io-wallet-user-func/src/infra/trial-system/client.ts
infra/resources/_modules/function_apps/locals.tf

chore: [SIW-1340] Updated header to trial system HTTP requests

---

infra/resources/_modules/function_apps/locals.tf

fix: updated env var

---

.changeset/few-fireants-tap.md
.changeset/metal-penguins-visit.md

Run changeset

---

.github/workflows/pr_infra.yaml
.github/workflows/release_infra.yaml

Update infra pipelines trigger paths
`_modules` folder was ignored

fix: Update infra pipelines trigger paths

---

infra/resources/_modules/cosmos/locals.tf

Increase maximum Cosmos RU in autoscale mode
Going live with a super reduced user subset

[SIW-1353] Increase maximum Cosmos RU in autoscale mode

---

infra/resources/_modules/apim/apim.tf

fix: change service_url in API IO web wallet in APIM

---

.github/workflows/user_function_deploy.yaml

fix: add prefix

---

infra/resources/_modules/apim/api/ioweb/user-function/_base_policy.xml

fix: [SIW-1388] updated APIM base policy API IO Web Wallet

---

.changeset/wild-forks-love.md
apps/io-wallet-user-func/src/app/main.ts
apps/io-wallet-user-func/src/infra/pid-issuer/client.ts

fix: fix ipzs call

---

.changeset/tricky-geese-carry.md
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-instance.ts
apps/io-wallet-user-func/src/wallet-instance.ts

This way we will revoke only valid wallet instances

fix: [SIW-1432] Updated revoke WI when creating a new one

---

infra/resources/_modules/function_apps/function_app_user.tf

Add autoscaler rules for User Function App. Conservative rules as traffic is still quite low
Dynamic horizontal scaling

Add autoscaler rules for User Function App

---

.changeset/perfect-carrots-itch.md
apps/io-wallet-user-func/src/infra/attestation-service/index.ts

fix: fix error concatenation

---

infra/resources/_modules/function_apps/function_app_user.tf
infra/resources/_modules/function_apps/variables.tf
infra/resources/prod/main.tf

Added configuration for application insights `io-p-ai-common` to function app user.
This way you can monitor the function through the common application insights and not a specific one

[SIW-1418] Add application insight configuration for Function App User

---

.changeset/lemon-apples-raise.md
apps/io-wallet-user-func/src/infra/pid-issuer/client.ts

The body sent to the API was wrong since it contained a `/` at the end

fix: add removeTrailingSlash to basepath

---

.github/workflows/user_function_deploy.yaml

Revert to the old deploy pipeline

fix: updated user_function_deploy github workflow

---

.changeset/mighty-mice-melt.md
apps/io-wallet-support-func/openapi.yaml
apps/io-wallet-support-func/package.json
apps/io-wallet-support-func/src/app/main.ts
apps/io-wallet-support-func/src/infra/azure/cosmos/wallet-instance.ts
apps/io-wallet-support-func/src/infra/azure/functions/get-current-wallet-instance-by-fiscal-code.ts
apps/io-wallet-support-func/src/infra/http/encoders/wallet-instance.ts
apps/io-wallet-support-func/src/infra/http/handlers/__test__/get-current-wallet-instance-by-fiscal-code.spec.ts
apps/io-wallet-support-func/src/infra/http/handlers/get-current-wallet-instance-by-fiscal-code.ts
apps/io-wallet-support-func/src/wallet-instance.ts
apps/io-wallet-user-func/src/infra/http/encoders/wallet-instance.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/get-current-wallet-instance.status.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/get-current-wallet-instance-status.ts
yarn.lock

1. Updated `support-func` openAPI spec
2. Added new `getCurrentWalletInstanceByFiscalCode` HTTP-triggered function with unit tests

feat: [SIW-1490] Added getCurrentWalletInstanceByFiscalCode function

---

infra/resources/_modules/function_apps/function_app_support.tf
infra/resources/_modules/function_apps/function_app_user.tf
infra/resources/_modules/function_apps/locals.tf
infra/resources/_modules/function_apps/nat_gateways.tf
infra/resources/_modules/function_apps/outputs.tf
infra/resources/_modules/function_apps/variables.tf
infra/resources/prod/data.tf
infra/resources/prod/main.tf

A new function app in the wallet domain is needed for support purposes

[SIW-1490] Add new function app support-func

---

infra/resources/_modules/function_apps/function_app_support.tf

Removed function app support autoscaler

---

infra/resources/_modules/function_apps/function_app_support.tf

Add function app support autoscaler

---

.github/workflows/support_function_deploy.yaml
infra/resources/_modules/function_apps/locals.tf
infra/resources/_modules/function_apps/variables.tf
infra/resources/prod/locals.tf
infra/resources/prod/main.tf

Added deploy pipeline for support function app and support env vars

---

infra/resources/_modules/function_apps/data.tf
infra/resources/_modules/function_apps/key_vault_secrets.tf
infra/resources/_modules/function_apps/variables.tf

[SIW-1490] Created key vault secret for Function App default key

---

infra/resources/_modules/cosmos/cosmos_accounts.tf
infra/resources/_modules/iam/variables.tf
infra/resources/prod/.terraform.lock.hcl
infra/resources/prod/README.md

Enable automatic failover between regions
Ensure that failover between regions is handled automatically

[CES-123] Enable automatic failover on Cosmos DB

---

infra/identity/prod/README.md
infra/identity/prod/data.tf
infra/identity/prod/main.tf
infra/repository/.terraform.lock.hcl
infra/resources/_modules/function_apps/key_vault_secrets.tf
infra/resources/_modules/monitoring/action_groups.tf
infra/resources/_modules/monitoring/outputs.tf
infra/resources/_modules/monitoring/variables.tf
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Create an Azure Action Group for the Wallet domain
Action groups should be managed individually by each team

[CES-136] Create Action Group for Wallet domain

---

.github/CODEOWNERS
CODEOWNERS
infra/resources/_modules/cdn/alerts.tf
infra/resources/_modules/cdn/variables.tf
infra/resources/_modules/cosmos/alerts.tf
infra/resources/_modules/cosmos/variables.tf
infra/resources/_modules/function_apps/alerts.tf
infra/resources/_modules/function_apps/function_app_support.tf
infra/resources/_modules/function_apps/function_app_user.tf
infra/resources/_modules/function_apps/variables.tf
infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/main.tf

Add alerts on Cosmos, Storage Account and Function Apps
Get notifications when things get bad

[CES-133] Add alerts on cloud resources

---

.changeset/red-countries-grow.md
apps/io-wallet-support-func/openapi.yaml
apps/io-wallet-support-func/src/infra/azure/cosmos/wallet-instance.ts
apps/io-wallet-support-func/src/infra/http/handlers/__test__/get-current-wallet-instance-by-fiscal-code.spec.ts
apps/io-wallet-user-func/host.json
apps/io-wallet-user-func/openapi.yaml
apps/io-wallet-user-func/src/app/config.ts
apps/io-wallet-user-func/src/app/main.ts
apps/io-wallet-user-func/src/infra/azure/cosmos/nonce.ts
apps/io-wallet-user-func/src/infra/azure/cosmos/wallet-instance.ts
apps/io-wallet-user-func/src/infra/azure/functions/set-current-wallet-instance-status.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/set-current-wallet-instance-status.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/set-current-wallet-instance-status.ts
apps/io-wallet-user-func/src/infra/pid-issuer/client.ts
apps/io-wallet-user-func/src/wallet-instance.ts
packages/io-wallet-common/src/__test__/jwk.spec.ts
packages/io-wallet-common/src/error.ts
packages/io-wallet-common/src/infra/azure/cosmos/config.ts
packages/io-wallet-common/src/infra/env.ts
packages/io-wallet-common/src/infra/http/config.ts
packages/io-wallet-common/src/infra/http/error.ts
packages/io-wallet-common/src/infra/pdv-tokenizer/client.ts
packages/io-wallet-common/tsconfig.json

1. Added `setCurrentWalletInstanceStatus` endpoint in `user` func
2. Added `503` response status code

feat: [SIW-1697] Added setCurrentWalletInstanceStatus endpoint

---

.changeset/seven-bugs-run.md
apps/io-wallet-user-func/src/infra/azure/appinsights/start.ts
apps/io-wallet-user-func/src/infra/azure/cosmos/nonce.ts
apps/io-wallet-user-func/src/infra/azure/cosmos/wallet-instance.ts
apps/io-wallet-user-func/src/infra/handlers/generate-entity-configuration.ts
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-attestation.ts
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-instance.ts
apps/io-wallet-user-func/src/infra/http/handlers/get-current-wallet-instance-status.ts
apps/io-wallet-user-func/src/infra/http/handlers/get-nonce.ts
apps/io-wallet-user-func/src/infra/http/handlers/set-current-wallet-instance-status.ts
apps/io-wallet-user-func/src/infra/http/handlers/set-wallet-instance-status.ts
apps/io-wallet-user-func/src/infra/pid-issuer/client.ts
apps/io-wallet-user-func/src/telemetry.ts

Add the function name in the properties sent to application insights

chore: [SIW-1402] Update appinsights exceptions telemetry

---

.changeset/gorgeous-gifts-yawn.md
apps/io-wallet-user-func/src/infra/azure/appinsights/start.ts

chore: update applicationinsights setting

---

.changeset/six-windows-explode.md
apps/io-wallet-user-func/package.json
apps/io-wallet-user-func/src/app/main.ts
apps/io-wallet-user-func/src/infra/azure/appinsights/start.ts
apps/io-wallet-user-func/src/infra/azure/appinsights/wrapper-handler.ts
apps/io-wallet-user-func/src/infra/pid-issuer/client.ts
yarn.lock

Added the createAppInsightsHandlerWrapper function and wrapped every HTTP handler inside it
This change fixes the issue where we couldn't see the requests in Application Insights
Manually

fix: [SIW-1774] Added app insights handler wrapper

---

.changeset/brave-islands-wave.md

[SIW-1479] run changeset

---

.changeset/fuzzy-garlics-design.md

[SIW-1857] Run changeset

---

yarn.lock

fix: updated yarn lock file

---

turbo.json

fix: updated turbo.json file

---

.changeset/hip-rockets-fry.md
apps/io-wallet-user-func/src/app/main.ts

chore: removed createLeaseCollectionIfNotExists property

---

.changeset/weak-yaks-report.md
apps/io-wallet-user-func/src/app/main.ts

fix: changed lease container name in addWalletInstanceToValidationQueue function

---

.changeset/old-wasps-promise.md
apps/io-wallet-user-func/src/app/config.ts
apps/io-wallet-user-func/src/infra/handlers/send-email-on-wallet-instance-creation.ts

fix: fixed email wallet instance creation title

---

package.json
turbo.json
yarn.lock

fix: updated turbo dependency

---

.changeset/strong-months-turn.md
apps/io-wallet-user-func/src/infra/handlers/send-email-on-wallet-instance-creation.ts
apps/io-wallet-user-func/src/infra/handlers/send-email-on-wallet-instance-revocation.ts

fix: updated io-web link

---

.changeset/dry-donuts-attend.md
apps/io-wallet-messages-func/src/message.ts

chore: Changed wallet message subject

---

.changeset/green-llamas-behave.md
apps/io-wallet-messages-func/host.json

chore: add visibilityTimeout to messages function app

---

apps/io-wallet-messages-func/src/infra/azure/storage/blob.ts

fix: updated messages function

---

.changeset/sweet-tips-kiss.md
apps/io-wallet-user-func/openapi.yaml

fix: fix isFiscalCodeWhitelisted operationId in openapi spec

---

apps/io-wallet-user-func/openapi.yaml

Updated `/wallet-attestation` endpoint openapi specification

fix: updated openapi

---

.changeset/lucky-pens-bake.md
apps/io-wallet-user-func/src/app/main.ts
apps/io-wallet-user-func/src/infra/azure/cosmos/wallet-instance.ts

chore: removed addWalletInstanceUserIdFunction

---

.changeset/ready-cases-switch.md
apps/io-wallet-user-func/src/certificates.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-attestation-v2.spec.ts

fix: revert temp CRL fix

---

.changeset/fruity-grapes-fall.md
apps/io-wallet-user-func/src/encoders/wallet-attestation.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-attestation-v2.spec.ts
apps/io-wallet-user-func/src/wallet-attestation.ts

chore: removed from wallet attestation header

---

.changeset/fluffy-walls-live.md
apps/io-wallet-user-func/src/wallet-attestation.ts

fix wallet attestation sd jwt

---

.changeset/lucky-coats-retire.md
apps/io-wallet-user-func/src/encoders/wallet-attestation.ts
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-attestation-v2.spec.ts
apps/io-wallet-user-func/src/infra/http/handlers/create-wallet-attestation-v2.ts
apps/io-wallet-user-func/src/wallet-attestation-mdoc.ts
apps/io-wallet-user-func/src/wallet-attestation.ts

chore: removed trust_chain in wallet attestation header and refactor code

---

.changeset/eleven-taxes-stare.md
apps/io-wallet-user-func/src/infra/handlers/generate-entity-configuration.ts
apps/io-wallet-user-func/src/wallet-provider.ts

fix: fix typo

---

.changeset/chatty-rocks-kick.md
apps/io-wallet-user-func/src/infra/http/handlers/__test__/create-wallet-attestation-v2.spec.ts
apps/io-wallet-user-func/src/wallet-attestation-mdoc.ts

fix: fix wallet attestation as mdoc cbor

---

infra/resources/_modules/function_apps/function_app_support.tf
infra/resources/_modules/function_apps/function_app_user.tf
infra/resources/_modules/function_apps/function_app_user_uat.tf

Added wallet action group to function app metric alert rules (storage account and health check)

[SIW-2355]: update alert rules

---

.changeset/open-dogs-glow.md
apps/io-wallet-user-func/src/wallet-attestation.ts

chore: [SIW-2935] Updated `vct` wallet attestation

---

infra/resources/_modules/function_apps/alerts.tf
infra/resources/_modules/function_apps/function_app_user_uat.tf

[SIW-2355] Removed ioperror ag from some alert rules
